[package]
name = "abstouch-nux"
version = "1.0.0"
authors = ["acedron <acedrons@yahoo.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "main"
path = "src/rust/main.rs"
